apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: elasticsearch-hpa
  namespace: elastic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: elasticsearch-es-data-nodes
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90