apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  podTemplate:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - prudentte-tools-workers-ng-m5-xlarge
  version: 8.4.3
  count: 3
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kibana
  namespace: elastic
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kibana.com.br
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601





